spring:
  datasource:
    url: ${vcap.services.PostgreSQL.credentials.url:jdbc:postgresql://localhost:5433/pets}
    username: ${vcap.services.PostgreSQL.credentials.username:postgres}
    password: ${vcap.services.PostgreSQL.credentials.password:postgres}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update