spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: NON_NULL

