spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pets
    username: sa
    password: sa
    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update